version: "3"
services:
  mongodb:
    container_name: "mongodb"
    image: 'bitnami/mongodb:latest'
    ports:
      - "27018:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  node:
    container_name: "restify"
    links:
      - mongodb
    build: .
    ports:
      - "8111:8040"

